type = "webpack"
main = "src/index.ts"
compatibility_date = "2024-08-17"

zone_id = ""
account_id = ""

name = "dcdn"
routes = ["dcdn.n0step.xyz/*"]
workers_dev = false
node_compat = true
webpack_config = "webpack.config.js"

kv_namespaces = [
  { binding = "Storage", id = "", preview_id = "" }
]